[package]
name = "bbox"
version.workspace = true
edition.workspace = true
license = "MIT OR Apache-2.0"

[dependencies]
ndarray.workspace = true
num = "0.4.3"
serde = { workspace = true, features = ["derive"], optional = true }

[features]
serde = ["dep:serde"]
default = ["serde"]
